name: "Paperight"
description: "A grand experiment in distributed print-on-demand"

url: http://localhost:4000
baseurl: /paperight-placeholder

paginate: 10

markdown: kramdown
permalink: none
highlighter: pygments